PL/Controllers/VentaProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class VentaProductoController : Controller
    {
        
         [HttpGet]
        public ActionResult GetAll()
        {
            ML.Result result = BL.Venta.GetAll();


            if(result.Correct)
            {

                ML.Venta venta = new ML.Venta();

                venta.Ventas = result.Objects;

                return View(venta);
            }
            else
            {
                ML.Venta venta = new ML.Venta();

                return View(venta);
            }
            

        }

           [HttpGet]
        public ActionResult Formulario()
        {
    

            return View();

        }
         [HttpPost]
        public ActionResult Formulario(ML.Venta venta)
        {

            ML.Result result = BL.Venta.Add(venta);

             if(result.Correct)
             {

                 return View();

             }
             else
             {
                 ViewBag.Message = "Error al guardar el producto ";
                 return PartialView();
             }
            return View();

        }


        //
        // GET: /VentaProducto/
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /VentaProducto/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /VentaProducto/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /VentaProducto/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /VentaProducto/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /VentaProducto/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /VentaProducto/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /VentaProducto/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PL/Views/VentaProducto/Formulario.cshtml
@model ML.Venta
@{
    ViewBag.Title = "Formulario";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container" style="margin-top:50px ">

    <div class="row">
        @using (Html.BeginForm("Formulario", "VentaProducto", FormMethod.Post))
        {
            <div class="container ">

                <div class="col-lg-10">
                    <div class="">
                        @Html.LabelFor(model => model.NombreProducto)
                        @Html.TextBoxFor(model => model.NombreProducto, new { @class = "form-control" })
                        @*@Html.DropDownListFor(model => model.Producto.)*@
                    </div>
                </div>
                <div class="col-lg-10 " >
                    <div class="">
                        @Html.LabelFor(model => model.Cantidad)
                        @Html.TextBoxFor(model => model.Cantidad, new { @class = "form-control" })

                    </div>
                </div>
                <div class="col-lg-10 " style="margin-top:5px;">
                    <div class="">
                        @Html.LabelFor(model => model.Total)
                        @Html.TextBoxFor(model => model.Total, new { @class = "form-control" })

                    </div>
                </div>


                <div class="col-lg-10" style="margin:15px;">
                    <div class="">


                        <input type="submit" class="btn btn-success" />


                    </div>
                </div>

            </div>
        }
    </div>

</div>

PL/Views/VentaProducto/GetAll.cshtml
@model ML.Venta
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <h1>Venta</h1>
        <div class="row">
            <div class="btn btn-success" style="margin:25px" >
                 @Html.ActionLink("+","Formulario")  

              
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <table class="table table-bordered table-responsive">
                <head>
                    <tr>
                        <th>Nombre</th>
                        <th>Cantidad</th>
                        <th>Total</th>
                        <th>Hora</th>

                    </tr>
                </head>
                <body>
                    @foreach (ML.Venta venta in Model.Ventas)
                    {
                        <tr>
                            <td>@venta.NombreProducto</td>

                            <td>@venta.Cantidad</td>
                            <td>@venta.Total</td>
                            <td>@venta.VentaHora</td>
                        </tr>
                    }

                </body>

            </table>
        </div>